### ISSUE TITLE
troubleshooting  nexus (CRITICAL)

### ISSUE THREAD

**Issue by fsadykov** [fuchicorp/main-fuchicorp#14]
Hello,

Our nexus is stopped responding to external traffic. I am not able to push my docker images. Please check our nexus and find out what is wrong. Please create a ticket if we need to change something. Please let me know if you need anything. 

http://nexus.fuchicorp.com/

Thank you

**Comment by fsadykov** [comment]
I am getting this error.

```
2019-05-03 01:21:42,306+0000 WARN  [ForkJoinPool.commonPool-worker-1] *SYSTEM com.orientechnologies.orient.core.metadata.schema.OClassImpl - $ANSI{green {db=audit}} Error adding clusterId '5' to index of class 'OIdentity'
com.orientechnologies.orient.core.exception.OStorageException: Storage audit is not opened.
	DB name="audit"
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.checkOpeness(OAbstractPaginatedStorage.java:3680)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.getPhysicalClusterNameById(OAbstractPaginatedStorage.java:2963)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.getClusterNameById(ODatabaseDocumentTx.java:1345)
	at com.orientechnologies.orient.core.metadata.schema.OClassImpl.addClusterIdToIndexes(OClassImpl.java:2626)
	at com.orientechnologies.orient.core.metadata.schema.OClassImpl.addPolymorphicClusterIds(OClassImpl.java:2763)
	at com.orientechnologies.orient.core.metadata.schema.OClassImpl.addPolymorphicClusterIdsWithInheritance(OClassImpl.java:2779)
	at com.orientechnologies.orient.core.metadata.schema.OClassImpl.addBaseClass(OClassImpl.java:2653)
	at com.orientechnologies.orient.core.metadata.schema.OClassImpl.setSuperClassesInternal(OClassImpl.java:443)
	at com.orientechnologies.orient.core.metadata.schema.OSchemaShared.fromStream(OSchemaShared.java:765)
	at com.orientechnologies.orient.core.type.ODocumentWrapperNoClass.reload(ODocumentWrapperNoClass.java:74)
	at com.orientechnologies.orient.core.metadata.schema.OSchemaShared.load(OSchemaShared.java:858)
	at com.orientechnologies.orient.core.metadata.OMetadataDefault$1.call(OMetadataDefault.java:172)
	at com.orientechnologies.orient.core.metadata.OMetadataDefault$1.call(OMetadataDefault.java:167)
	at com.orientechnologies.common.concur.resource.OSharedContainerImpl.getResource(OSharedContainerImpl.java:62)
	at com.orientechnologies.orient.core.storage.OStorageAbstract.getResource(OStorageAbstract.java:143)
	at com.orientechnologies.orient.core.metadata.OMetadataDefault.init(OMetadataDefault.java:167)
	at com.orientechnologies.orient.core.metadata.OMetadataDefault.load(OMetadataDefault.java:89)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.initAtFirstOpen(ODatabaseDocumentTx.java:3210)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:271)
	at org.sonatype.nexus.orient.DatabaseManagerSupport.connect(DatabaseManagerSupport.java:174)
	at org.sonatype.nexus.orient.DatabaseInstanceImpl.doStart(DatabaseInstanceImpl.java:56)
	at org.sonatype.goodies.lifecycle.LifecycleSupport.start(LifecycleSupport.java:104)
	at org.sonatype.goodies.lifecycle.Lifecycles.start(Lifecycles.java:44)
	at org.sonatype.nexus.orient.DatabaseManagerSupport.createInstance(DatabaseManagerSupport.java:306)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at org.sonatype.nexus.orient.DatabaseManagerSupport.instance(DatabaseManagerSupport.java:285)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```
